# Site settings
title: John Field MSc
tag_text: John Field, PHP, Symfony, Agile, Walthamstow, London
description: John Field's GitHub page.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
