repository: JohnField/johnfield.github.io

# https://github.com/pages-themes/cayman
theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins

# Site settings
title: John Field's GitHub Site
google_analytics: UA-93000729-1

# Build settings
markdown: kramdown
exclude: ["docker-compose.yml", "README.md"]
sass:
  style: compressed

# See https://github.com/JohnField/googledoc-as-githubpage
# The ID of the Google Doc to be embedded.
googledoc_id: 1cEF03nKm7c7qV8CoDSyytBhJTB0CxmXm42kPKp2r71o
