#theme: jekyll-theme-cayman
theme: jekyll-theme-minimal
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap

# Configuration
repository: JohnField/johnfield.github.io
url: https://johnfield.github.io/
title: John Field
description: John Field's GitHub Pages
logo: https://en.gravatar.com/avatar/fe934364550d859ff5da98ba631f588b.png?size=200
google_analytics: UA-93000729-1

# Build
exclude: ['.gitignore', 'docker-compose.yml', 'README.md']
markdown: kramdown
incremental: true

# See https://github.com/JohnField/googledoc-as-githubpage
# The ID of the Google Doc to be embedded.
googledoc_id: 1cEF03nKm7c7qV8CoDSyytBhJTB0CxmXm42kPKp2r71o
