# Site settings
title: John Field MSc
_tag_text: John Field, PHP, Symfony, Agile, Walthamstow, London
tag_text: John Field's GitHub Site
description: A GitHub Site for John Field.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
