jekyll:
    # https://kristofclaes.github.io/2016/06/19/running-jekyll-locally-with-docker/
    # docker-compose logs --follow johnfield.github.io
    # docker exec -it johnfield.github.io bash
    image: jekyll/jekyll
    #image: jekyll/jekyll:pages
    container_name: johnfield.github.io
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
