version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    container_name: johnfield.github.io
    # user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
    tty: true