version: '3'
services:
  jekyll:
    image: starefossen/github-pages
    container_name: johnfield.github.io
    # user: "${USER_ID}:${GROUP_ID}"
    environment:
      - "JEKYLL_GITHUB_TOKEN:${JEKYLL_GITHUB_TOKEN}"
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
    tty: true